### ISSUE TITLE
.git/index unreadable

### ISSUE THREAD

**Issue by d-glenz** [d-glenz/extended-wyag#1]
Sometimes, `ewyag ls-files -s` breaks with a `UnicodeDecodeError`:
`Traceback (most recent call last):
  File "/media/dominik/Data/WorkspaceNew/python/wyag/.venv/bin/ewyag", line 11, in <module>
    load_entry_point('ewyag', 'console_scripts', 'ewyag')()
  File "/media/dominik/Data/WorkspaceNew/python/wyag/ewyag/main.py", line 6, in main
    ewyag.libwyag.subcommand_main()
  File "/media/dominik/Data/WorkspaceNew/python/wyag/ewyag/libwyag.py", line 184, in subcommand_main
    target_function(args)
  File "/media/dominik/Data/WorkspaceNew/python/wyag/ewyag/commands.py", line 141, in cmd_ls_files
    idx = read_index()
  File "/media/dominik/Data/WorkspaceNew/python/wyag/ewyag/index.py", line 169, in read_index
    entries.append(GitIndexEntry(*(fields + (path.decode(),))))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 2: invalid continuation byte`

**Comment by d-glenz** [comment]
Fixed with e713339 - needed to skip extensions.
